---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tradlick/public_html/
    - rm -rf $DEPLOYPATH && cp -r ./ $DEPLOYPATH
    - cd $DEPLOYPATH && composer install && echo "Success"
    # && composer update && npm install && npm update && npm run prod
