---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tradlick/
    - rm -rf $DEPLOYPATH/public_html/* && rm -rf $DEPLOYPATH/framework/* && cp -r ./ $DEPLOYPATH/framework && mv -r $DEPLOYPATH/framework/public/* $DEPLOYPATH/public_html/ && cat index.php | xclip -i && echo "ini_set('eaccelerator.enable', 0);" > index.php && xclip -o >> index.php
    - cd $DEPLOYPATH && composer install #
    # && composer update && npm install && npm update && npm run prod
