---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tradlick/public_html
    - /bin/cp -r ./ $DEPLOYPATH/framework && /bin/cp -r $DEPLOYPATH/framework/public/* $DEPLOYPATH/
    - rm -rf $DEPLOYPATH/* && rm -rf $DEPLOYPATH/framework/* && cd $DEPLOYPATH/framework/ && composer install #
    # && composer update && npm install && npm update && npm run prod
    # rm -rf $DEPLOYPATH/* && rm -rf $DEPLOYPATH/framework/* &&
